[package]
name = "44780/portfolio"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"

[server-dependencies]
profileservice = "firebird702/profileservice@1.1.0"